"""
Base class for annotation assessment.

All assessors should inherit from this class and implement the required methods.
"""

from abc import ABC, abstractmethod
from typing import Dict, Any, Optional
from dataclasses import dataclass


@dataclass
class AssessmentResult:
    """Result of an annotation assessment."""
    is_correct: bool
    assessment_result: str
    explanation: str
    suggested_correction: Optional[str] = None
    metadata: Dict[str, Any] = None
    
    def __post_init__(self):
        if self.metadata is None:
            self.metadata = {}


class BaseAssessor(ABC):
    """
    Abstract base class for annotation assessors.
    
    Assessors evaluate the quality of LLM-generated annotations by comparing
    them against golden truth annotations.
    """
    
    def __init__(self, model: str = "gpt-4o"):
        """
        Initialize the assessor.
        
        Args:
            model: LLM model to use for assessment
        """
        self.model = model
    
    @abstractmethod
    def assess(
        self, 
        llm_annotation: Any, 
        golden_annotation: Any,
        context: Optional[Dict[str, Any]] = None
    ) -> AssessmentResult:
        """
        Assess the quality of an LLM annotation against golden truth.
        
        Args:
            llm_annotation: The annotation generated by the LLM
            golden_annotation: The golden truth annotation
            context: Additional context (e.g., question, problem description)
            
        Returns:
            AssessmentResult with correctness judgment and explanation
        """
        pass
    
    @abstractmethod
    def get_assessment_criteria(self) -> Dict[str, Any]:
        """
        Get the criteria used for assessment.
        
        Returns:
            Dictionary describing assessment criteria and standards
        """
        pass
    
    def validate_inputs(self, llm_annotation: Any, golden_annotation: Any) -> bool:
        """
        Validate that inputs are in the expected format.
        
        Args:
            llm_annotation: LLM annotation to validate
            golden_annotation: Golden annotation to validate
            
        Returns:
            True if inputs are valid, False otherwise
        """
        # Default implementation - can be overridden by subclasses
        return True
